service: sangue
app: skoll
tenant: viniciusgomes
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: skoll

functions:
  getBloodType:
    handler: handler.getBloodType
    events:
      - http:
          path: sangue
          method: get
          cors:
            origin: '*'
            maxAge: 86400
