service: arquivos
app: skoll
tenant: viniciusgomes
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: skoll

functions:
  uploadUserPhoto:
    handler: handler.uploadUserPhoto
    events:
      - http:
          path: arquivo/user
          method: get
          cors:
            origin: '*'
            maxAge: 86400
  uploadAnimalPhoto:
    handler: handler.uploadAnimalPhoto
    events:
      - http:
          path: arquivo/animal
          method: get
          cors:
            origin: '*'
            maxAge: 86400
