service: user
app: skoll
tenant: viniciusgomes
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: skoll

functions:
  readUsers:
    handler: handler.readUsers
    events:
      - http:
          path: user
          method: get
          cors:
            origin: '*'
            maxAge: 86400
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
          cors:
            origin: '*'
            maxAge: 86400
